# Generated by Django 4.2.30 on 2026-06-08 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cedula_rnc', models.CharField(max_length=20, unique=True, verbose_name='Cédula / RNC')),
                ('no_tarjeta_cr', models.CharField(max_length=19, verbose_name='No. Tarjeta de Crédito')),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Límite de Crédito')),
                ('tipo_persona', models.CharField(choices=[('Fisica', 'Física'), ('Juridica', 'Jurídica')], default='Fisica', max_length=15)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('tanda_labor', models.CharField(choices=[('Matutina', 'Matutina'), ('Vespertina', 'Vespertina'), ('Nocturna', 'Nocturna')], default='Matutina', max_length=15)),
                ('porc_comision', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje Comisión (%)')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.marca', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción/Nombre')),
                ('no_chasis', models.CharField(max_length=50, unique=True, verbose_name='No. Chasis')),
                ('no_motor', models.CharField(max_length=50, unique=True, verbose_name='No. Motor')),
                ('no_placa', models.CharField(max_length=20, unique=True, verbose_name='No. Placa')),
                ('precio_por_dia', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, verbose_name='Precio por Día')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Rentado', 'Rentado'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_app.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_app.modelo', verbose_name='Modelo')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_app.tipocombustible', verbose_name='Tipo de Combustible')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_app.tipovehiculo', verbose_name='Tipo de Vehículo')),
            ],
        ),
        migrations.CreateModel(
            name='RentaDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Renta')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución Estimada')),
                ('monto_x_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto por Día')),
                ('cantidad_dias', models.IntegerField(verbose_name='Cantidad de Días')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('comision_calculada', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Comisión Calculada')),
                ('estado', models.CharField(choices=[('Activo', 'Activo / Rentado'), ('Devuelto', 'Devuelto con Éxito')], default='Activo', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_app.cliente', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_app.empleado', verbose_name='Empleado Ejecutor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_app.vehiculo', verbose_name='Vehículo')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_ralladuras', models.BooleanField(default=False, verbose_name='Tiene Ralladuras')),
                ('cantidad_combustible', models.CharField(choices=[('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('Lleno', 'Lleno')], default='1/2', max_length=10, verbose_name='Cantidad de Combustible')),
                ('tiene_goma_repuesto', models.BooleanField(default=True, verbose_name='Tiene Goma de Repuesto')),
                ('tiene_gato', models.BooleanField(default=True, verbose_name='Tiene Gato Hidráulico')),
                ('tiene_roturas_cristal', models.BooleanField(default=False, verbose_name='Tiene Roturas de Cristal')),
                ('estado_gomas_delanteras_ok', models.BooleanField(default=True, verbose_name='Gomas Delanteras en Buen Estado')),
                ('estado_gomas_traseras_ok', models.BooleanField(default=True, verbose_name='Gomas Traseras en Buen Estado')),
                ('fecha_inspeccion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inspección')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.cliente', verbose_name='Cliente')),
                ('empleado_inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent_app.empleado', verbose_name='Inspector')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.vehiculo', verbose_name='Vehículo')),
            ],
        ),
    ]
