# Generated by Django 4.2.30 on 2026-06-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccion',
            name='estado_gomas_delanteras_ok',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='estado_gomas_traseras_ok',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='goma_delantera_der',
            field=models.BooleanField(default=True, verbose_name='Goma Delantera Derecha (Buen Estado)'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='goma_delantera_izq',
            field=models.BooleanField(default=True, verbose_name='Goma Delantera Izquierda (Buen Estado)'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='goma_trasera_der',
            field=models.BooleanField(default=True, verbose_name='Goma Trasera Derecha (Buen Estado)'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='goma_trasera_izq',
            field=models.BooleanField(default=True, verbose_name='Goma Trasera Izquierda (Buen Estado)'),
        ),
    ]
